[workspace]
authors = ["Ajith Pattammattel <pattammattel@bnl.gov>"]
channels = ["conda-forge"]
name = "xmidas"
version = "0.1.0"
platforms = ["osx-arm64", "linux-64"] 

[system-requirements]
# This tells Pixi that your Linux target is RHEL 9 (glibc 2.34)
libc = { family = "glibc", version = "2.34" }

[tasks]
# This creates a shortcut so you just run 'pixi run gui'
# I named it 'gui' here for brevity, but 'run-xmidas' works too!
run-xmidas = "python -m xmidas.main"

[dependencies]
python = "3.12.*"
h5py = ">=3.15.1,<4"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.0,<4"
scikit-image = ">=0.26.0,<0.27"
scikit-learn = ">=1.8.0,<2"
scipy = ">=1.17.0,<2"
tifffile = ">=2026.1.28,<2027"
packaging = ">=26.0,<27"
pyqt6 = ">=6.8.1,<7"

[pypi-dependencies]
pystackreg = ">=0.2.8, <0.3"
xraydb = ">=4.5.8, <5"
pyqtgraph = ">=0.14.0, <0.15"
opencv-python = ">=4.13.0.92, <5"

